### ISSUE TITLE
Feedback on version 1.0.0-rc3

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/riscv-acpi-rimt#14]
1. ARC felt the abbreviation of IO as I in "RIMT" was a bit unfortunate. We suggest that the TG consider renaming the table as "RISC-V IO Remapping (RIOR)" table. 
2. A few instance of PCI should be renamed to PCIe
3. "The device node structure can be further classified as PCIe and platform device structures bound to an IOMMU." -> "The device node structure can be further classified as PCIe root complex and platform device structures bound to an IOMMU."
4. It was unclear whether the specification allows associating an IOMMU with multiple root complex nodes. If that is not allowed then it should be clarified. If it does then any rules related to source IDs not overlapping should be clarified.
5. In PCIe 6.0, the segment number in the TLP is 8-bit wide. The tables have a 2 byte field for the segment number. Is this an error?
6. The RISC-V IOMMU supports a maximum of 16 wire interrupts. The table has a 2 byte field for number of wire interrupts. Should this be a 1 byte field?
7. "This field is the offset of the RISC-V IOMMU node to the start of the RIMT table" -> "This field is the offset of the RISC-V IOMMU node from the start of the RIMT table"

@vlsunil

**Comment by vlsunil** [comment]
Thanks again for your kind feedback. Responses below.

>>    ARC felt the abbreviation of IO as I in "RIMT" was a bit unfortunate. We suggest that the TG consider renaming the table as "RISC-V IO Remapping (RIOR)" table.

Actually, abbreviating IO as I seems to be a standard practice for ACPI table signature. There are only 4 letters which need to be unique. For ex: IVRS stands for IO Virtualization Reporting Structure. RIMT is already approved by ASWG as well.
 >>    A few instance of PCI should be renamed to PCIe

Okay.
>>   "The device node structure can be further classified as PCIe and platform device structures bound to an IOMMU." -> "The device node structure can be further classified as PCIe root complex and platform device structures bound to an IOMMU."

Sure.
>>    It was unclear whether the specification allows associating an IOMMU with multiple root complex nodes. If that is not allowed then it should be clarified. If it does then any rules related to source IDs not overlapping should be clarified.

Good catch!. It should be supported but source IDs should not overlap when segment number is same. Firmware must indicate to the OS using _DSM that it should preserve boot configurations. Will add this clarification.
 >>  In PCIe 6.0, the segment number in the TLP is 8-bit wide. The tables have a 2 byte field for the segment number. Is this an error?

Actually, it is matching MCFG field (defined by PCI FW spec) and _SEG return value. They are 2 byte fields.
 >>  The RISC-V IOMMU supports a maximum of 16 wire interrupts. The table has a 2 byte field for number of wire interrupts. Should this be a 1 byte field?

Correct. It is made 2 byte field so that next field is aligned. We can make it 1 byte field and add a reserved 1 byte field. Would you prefer that way?

 >>   "This field is the offset of the RISC-V IOMMU node to the start of the RIMT table" -> "This field is the offset of the RISC-V IOMMU node from the start of the RIMT table"

Sure.

**Comment by ved-rivos** [comment]
> Actually, it is matching MCFG field (defined by PCI FW spec) and _SEG return value. They are 2 byte fields.

Thats consistent with ACPI but does not match the wire protocol. This looks fine then.

> Correct. It is made 2 byte field so that next field is aligned. We can make it 1 byte field and add a reserved 1 byte field. Would you prefer that way?

Lets keep it as is. Even with 1 byte it will be wider than the number of wires supported by the IOMMU.

We will discuss the name and your input on precedence in the next ARC. If have a new draft with the other changes then please send a PDF.
